config {
  type: "table",
  schema: "work",
  description: "Mapping di alimentazione della tabella DIM_AGENZIA"
  /* Parametri ODI: GOV_DWH.V_DAT_SCHED_TWS */
}

pre_operations {
  -- [Drop flow table (I$)]
drop table /* ODI_TEMP: UNIQUE_STEP_TAG */

  -- [Create flow table (I$)]
create table /* ODI_TEMP: UNIQUE_STEP_TAG */
 (
 COD_AGENZIA	STRING null,
	DESC_AGENZIA	STRING null,
	FLG_OPERATIVA	CHAR(1) null,
	DAT_CHIUSURA	DATE null,
	COD_ABI	STRING null,
	COD_CAB	STRING null,
	COD_PROVINCIA	STRING null,
	COD_NAZIONE	STRING null,
	DESC_LOCALITA	STRING null,
	DESC_INDIRIZZO	STRING null,
	COD_CIN	STRING null,
	COD_CAB_COMUNE	STRING null,
	COD_CIN_COMUNE	STRING null,
DAT_INIZIO_VALIDITA	DATE null,
DAT_FINE_VALIDITA	DATE null,
   IND_UPDATE		CHAR(1)
)

  -- [delete previous check sum]
delete from 	/* ODI_INTERNAL: SNP_CHECK_TAB */
where	CATALOG_NAME	= '/* ODI_EXPR */'
and	SCHEMA_NAME	= '/* schema */'
and	ORIGIN		= '(19387)GOV_DWH - DataWareHouse.MAP_DIM_AGENZIA'
and	ERR_TYPE		= 'F'

  -- [Analyze integration table]
use		/* ODI_EXPR */
create statistics	/* ODI_EXPR */
on		/* ODI_TEMP: UNIQUE_STEP_TAG */
		(COD_AGENZIA,
		DAT_INIZIO_VALIDITA,
		DAT_FINE_VALIDITA,
		DESC_AGENZIA,
		FLG_OPERATIVA,
		DAT_CHIUSURA,
		COD_ABI,
		COD_CAB,
		COD_PROVINCIA,
		COD_NAZIONE,
		DESC_LOCALITA,
		DESC_INDIRIZZO,
		COD_CIN,
		COD_CAB_COMUNE,
		COD_CIN_COMUNE)
with sample 10 percent;

  -- [delete null AK from controlled table]
delete from /* ODI_TEMP: UNIQUE_STEP_TAG */ I
where (I.COD_AGENZIA IS NULL )

}

-- Scenario ODI: DATAWAREHOUSE_MAP_DIM_AGENZIA v001
-- Variabili: GOV_DWH.V_MODULE, GOV_DWH.V_DAT_SCHED_TWS
-- NOTA: verifica i commenti TODO prima di eseguire in produzione

select
	H_AGENZIA.COD_AGENZIA	COD_AGENZIA,
	(UPPER(S_AGENZIA.DESC_AGENZIA))	DESC_AGENZIA,
	(CASE
  WHEN S_AGENZIA.FLG_ESTINZIONE = '1' THEN '0'
  ELSE COALESCE(/* schema */.F_GET_RACCORDO('DIM_AGENZIA', 'FLG_OPERATIVA', S_AGENZIA.IDC_CHIUSA_OPERATIVA), '1')
END)	FLG_OPERATIVA,
	S_AGENZIA.DAT_CHIUSURA	DAT_CHIUSURA,
	S_AGENZIA.COD_ABI	COD_ABI,
	S_AGENZIA.COD_CAB	COD_CAB,
	(UPPER(S_AGENZIA.COD_PROVINCIA))	COD_PROVINCIA,
	(UPPER(S_AGENZIA.COD_NAZIONE))	COD_NAZIONE,
	(UPPER(S_AGENZIA.DESC_LOCALITA))	DESC_LOCALITA,
	(UPPER(S_AGENZIA.DESC_SEDE_OPERATIVA))	DESC_INDIRIZZO,
	S_AGENZIA.COD_CIN	COD_CIN,
	S_AGENZIA.COD_CAB_COMUNE	COD_CAB_COMUNE,
	S_AGENZIA.COD_CIN_COMUNE	COD_CIN_COMUNE,
        PARSE_DATE('%Y%m%d', '${dataform.projectConfig.vars.dat_sched_tws}') DAT_INIZIO_VALIDITA,
        PARSE_DATE('%Y%m%d', '24000101') DAT_FINE_VALIDITA,
        'I' IND_UPDATE
from	${ref("h_agenzia")} /* datavault */ H_AGENZIA  INNER JOIN  ${ref("s_agenzia")} /* datavault */ S_AGENZIA
    ON  H_AGENZIA.SEQ_AGENZIA = S_AGENZIA.SEQ_AGENZIA
where	(1=1)
 and (PARSE_DATE('%Y%m%d', '${dataform.projectConfig.vars.dat_sched_tws}') BETWEEN S_AGENZIA.DAT_INIZIO_VALIDITA
                                                  AND S_AGENZIA.DAT_FINE_VALIDITA)
